package sha_la;
import java.util.*;
import java.lang.*;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
public class SHA_512 {
	public static String encryptThisString(String input)
    {
        try {
            // getInstance() method is called with algorithm SHA-512
            MessageDigest md = MessageDigest.getInstance("SHA-512");
  
            // digest() method is called
            // to calculate message digest of the input string
            // returned as array of byte
            byte[] messageDigest = md.digest(input.getBytes());
  
            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);
  
            // Convert message digest into hex value
            String hashtext = no.toString(16);
            
            StringBuilder sb= new StringBuilder(hashtext);
            
            
            // call to the methods you want to benchmark
//            long start = System.currentTimeMillis();
            while(sb.length()<32) {
            	sb.append("0");
            }
//            long end = System.currentTimeMillis();
//            long elapsedTime = end - start;
//            System.out.println(elapsedTime);

            // Add preceding 0s to make it 32 bit
            
//            while (hashtext.length() < 32) {
//                hashtext = "0" + hashtext;
//            }

       
            
            
            
            // return the HashText
            return hashtext;
        }
  
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
	
	public static void main(String args[]) throws NoSuchAlgorithmException
    {
  
        System.out.println("HashCode Generated by SHA-512 for: ");
  
        
  
        String s1 = "SHIV0";
        System.out.println("\n" + s1 + " : " + encryptThisString(s1));
    }

}
